# Generated by Django 2.2.1 on 2019-09-22 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICL_ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel_number', phone_field.models.PhoneField(max_length=31, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('person', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(related_name='contact_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotact_created_by', to=settings.AUTH_USER_MODEL)),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.ICL_ContactCategoryModel')),
            ],
            options={
                'verbose_name': 'ICL Contact Detail',
                'verbose_name_plural': 'ICL Contact Details',
                'ordering': ('-date_created',),
            },
        ),
    ]
