# Generated by Django 2.2.1 on 2019-09-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190926_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihe_contactmodel',
            name='org_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.IHE_ContactCategoryModel'),
        ),
    ]
