# Generated by Django 2.2.1 on 2019-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190926_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihe_contactmodel',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='shs_contactmodel',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date Updated'),
        ),
    ]
