# Generated by Django 2.2.1 on 2019-09-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICL_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ICL Contact Category',
                'verbose_name_plural': 'ICL Contact Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IHE_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'IHE Contact Category',
                'verbose_name_plural': 'IHE Contact Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SHS_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SHS Contact Category',
                'verbose_name_plural': 'SHS Contact Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SHS_ContactModel',
            fields=[
                ('shs_id', models.AutoField(primary_key=True, serialize=False)),
                ('shs_name', models.CharField(max_length=255)),
                ('c_number_tel', models.BigIntegerField(null=True)),
                ('c_number_cp', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('shs_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerconsultant.SHS_ContactCategoryModel')),
            ],
            options={
                'verbose_name': 'SHS Contact Detail',
                'verbose_name_plural': 'SHS Contact Details',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='IHE_ContactModel',
            fields=[
                ('ihe_id', models.AutoField(primary_key=True, serialize=False)),
                ('ihe_name', models.CharField(max_length=255)),
                ('c_number_tel', models.BigIntegerField(null=True)),
                ('c_number_cp', models.BigIntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('ihe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerconsultant.IHE_ContactCategoryModel')),
            ],
            options={
                'verbose_name': 'IHE Contact Detail',
                'verbose_name_plural': 'IHE Contact Details',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ICL_ContactModel',
            fields=[
                ('icl_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('telephone_number', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('phone_number', models.BigIntegerField(null=True, unique=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('c_person', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
                ('org_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerconsultant.ICL_ContactCategoryModel')),
            ],
            options={
                'verbose_name': 'ICL Contact Detail',
                'verbose_name_plural': 'ICL Contact Details',
                'ordering': ('-date_created',),
            },
        ),
    ]
