# Generated by Django 2.2.1 on 2019-09-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('title', models.CharField(max_length=255, null=True)),
                ('cs_id', models.AutoField(primary_key=True, serialize=False)),
                ('tuition_percentage', models.SmallIntegerField(null=True)),
                ('misc_fee_status', models.BooleanField(choices=[(True, 'PAID'), (False, 'UNPAID')])),
                ('reg_fee_status', models.BooleanField(choices=[(True, 'PAID'), (False, 'UNPAID')])),
                ('stud_fee_status', models.BooleanField(choices=[(True, 'ENROLLED'), (False, 'DROP')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('status', models.CharField(choices=[('regular', 'RegularClass'), ('nightclass', 'NightClass')], default='regular', max_length=50)),
                ('course', models.CharField(choices=[('bsit', 'BSIT'), ('bsba', 'BSBA'), ('shs', 'SHS')], default='bsit', max_length=50)),
                ('payment_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_amount_per_unit', models.BigIntegerField(null=True)),
                ('cash_miscellaneous_fee', models.BigIntegerField(null=True)),
                ('cash_lab_fee', models.BigIntegerField(null=True)),
                ('cash_registration_fee', models.BigIntegerField(null=True)),
                ('ins_amount_unit', models.BigIntegerField(null=True)),
                ('ins_miscellaneous_fee', models.BigIntegerField(null=True)),
                ('ins_lab_fee', models.BigIntegerField(null=True)),
                ('ins_registration_fee', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='SanctionSetting',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_sanction', models.CharField(max_length=255)),
                ('second_sanction', models.CharField(max_length=255)),
                ('third_sanction', models.CharField(max_length=255)),
                ('fourth_sanction', models.CharField(max_length=255)),
                ('fifth_sanction', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sanction Settings',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.DateField(unique=True)),
                ('end_year', models.DateField(unique=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'School Year',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TargetSheet',
            fields=[
                ('ts_id', models.AutoField(primary_key=True, serialize=False)),
                ('corporate', models.BigIntegerField(null=True)),
                ('retail', models.BigIntegerField(null=True)),
                ('owwa', models.BigIntegerField(null=True)),
                ('seniorhigh', models.BigIntegerField(null=True)),
                ('higher_ed', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Target Sheet',
                'ordering': ['-date_created', '-date_updated'],
            },
        ),
    ]
