# Generated by Django 2.2.1 on 2019-08-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('cs_id', models.AutoField(primary_key=True, serialize=False)),
                ('tuition_percentage', models.SmallIntegerField(null=True)),
                ('misc_fee_status', models.BooleanField(choices=[(True, 'PAID'), (False, 'UNPAID')])),
                ('reg_fee_status', models.BooleanField(choices=[(True, 'PAID'), (False, 'UNPAID')])),
                ('stud_fee_status', models.BooleanField(choices=[(True, 'ENROLLED'), (False, 'DROP')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('payment_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_amount_per_unit', models.BigIntegerField(null=True)),
                ('cash_miscellaneous_fee', models.BigIntegerField(null=True)),
                ('cash_lab_fee', models.BigIntegerField(null=True)),
                ('cash_registration_fee', models.BigIntegerField(null=True)),
                ('ins_amount_unit', models.BigIntegerField(null=True)),
                ('ins_miscellaneous_fee', models.BigIntegerField(null=True)),
                ('ins_lab_fee', models.BigIntegerField(null=True)),
                ('ins_registration_fee', models.BigIntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Details',
            },
        ),
        migrations.CreateModel(
            name='SanctionSetting',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('quota_status', models.CharField(max_length=255)),
                ('first_sanction', models.CharField(max_length=255)),
                ('second_sanction', models.CharField(max_length=255)),
                ('third_sanction', models.CharField(max_length=255)),
                ('fourth_sanction', models.CharField(max_length=255)),
                ('fifth_sanction', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sanction Settings',
            },
        ),
        migrations.CreateModel(
            name='TargetSheet',
            fields=[
                ('TargetSheet_ID', models.AutoField(primary_key=True, serialize=False)),
                ('schoolyear', models.DateTimeField(null=True, unique_for_year='school_year')),
                ('corporate', models.BigIntegerField(null=True)),
                ('retail', models.BigIntegerField(null=True)),
                ('owwa', models.BigIntegerField(null=True)),
                ('seniorhigh', models.BigIntegerField(null=True)),
                ('higher_ed', models.BigIntegerField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Target Sheet',
            },
        ),
    ]
