# Generated by Django 2.2.1 on 2019-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetsheet',
            old_name='schoolyear',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='targetsheet',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
