# Generated by Django 2.2.1 on 2019-09-24 07:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyear',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='active_year',
            field=models.BooleanField(default=False, help_text='This is Current School Year. There Can Only be one.'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.DateField(unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.DateField(unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))]),
        ),
    ]
