# Generated by Django 2.2.1 on 2019-09-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'School Year'},
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='created_on',
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='date_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
