# Generated by Django 2.2.1 on 2019-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0002_auto_20190920_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctionsetting',
            name='fifth_sanction',
            field=models.CharField(default='Termination', max_length=255),
        ),
        migrations.AlterField(
            model_name='sanctionsetting',
            name='first_sanction',
            field=models.CharField(default='Verbal Warning', max_length=255),
        ),
        migrations.AlterField(
            model_name='sanctionsetting',
            name='fourth_sanction',
            field=models.CharField(default='Six Days Suspension', max_length=255),
        ),
        migrations.AlterField(
            model_name='sanctionsetting',
            name='second_sanction',
            field=models.CharField(default='Written Explanation', max_length=255),
        ),
        migrations.AlterField(
            model_name='sanctionsetting',
            name='third_sanction',
            field=models.CharField(default='Three Days Suspension', max_length=255),
        ),
    ]
