# Generated by Django 2.2.1 on 2019-08-22 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0002_auto_20190822_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsheet',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
