# Generated by Django 2.2.1 on 2019-08-22 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0003_auto_20190822_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsheet',
            name='start_date',
            field=models.DateTimeField(blank=None, default=django.utils.timezone.now, null=None),
        ),
    ]
