# Generated by Django 2.2.1 on 2019-09-10 12:29

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0003_auto_20190910_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=partial_date.fields.PartialDateField(unique=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=partial_date.fields.PartialDateField(unique=True),
        ),
    ]
