# Generated by Django 2.2.1 on 2019-08-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0004_auto_20190822_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='targetsheet',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='targetsheet',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='targetsheet',
            name='start_date',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('regular', 'RegularClass'), ('nc', 'NightClass')], default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='targetsheet',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='targetsheet',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='targetsheet',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
