# Generated by Django 2.2.1 on 2019-09-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0004_auto_20190910_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.DateField(unique=True),
        ),
    ]
