# Generated by Django 2.2.1 on 2019-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0005_auto_20190823_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('regular', 'RegularClass'), ('nightclass', 'NightClass')], default='regular', max_length=50),
        ),
    ]
