# Generated by Django 2.2.1 on 2019-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0005_auto_20190910_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.DateField(unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.DateField(unique_for_year=True),
        ),
    ]
