# Generated by Django 2.2.1 on 2019-08-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0006_auto_20190823_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionsetting',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='sanctionsetting',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='sanctionsetting',
            name='quota_status',
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sanctionsetting',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
