# Generated by Django 2.2.1 on 2019-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0006_auto_20190917_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.DateField(unique=True),
        ),
    ]
