# Generated by Django 2.2.1 on 2019-09-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centermanager', '0007_auto_20190917_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='end_year',
            field=models.DateField(unique_for_year='end_year'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='start_year',
            field=models.DateField(unique_for_year='start_year'),
        ),
    ]
