# Generated by Django 2.2.1 on 2019-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermarketingprofile',
            name='status',
            field=models.CharField(choices=[('Budgetary', 'Budgetary'), ('ICL', 'ICL'), ('SHS', 'SHS'), ('IHE', 'IHE')], default='Budgetary', max_length=50),
        ),
    ]
