# Generated by Django 2.2.1 on 2019-09-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermarketingprofile',
            name='username',
        ),
    ]
