# Generated by Django 2.2.1 on 2019-09-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usermarketingprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_budgetary',
            field=models.BooleanField(blank=True, default=False, verbose_name='BUDGETARY'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_icl',
            field=models.BooleanField(blank=True, default=False, verbose_name='ICL'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_ihe',
            field=models.BooleanField(blank=True, default=False, verbose_name='IHE'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_shs',
            field=models.BooleanField(blank=True, default=False, verbose_name='SHS'),
        ),
    ]
