# Generated by Django 2.2.1 on 2019-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermarketingprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermarketingprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='usermarketingprofile',
            name='role',
            field=models.CharField(choices=[('CenterManager', 'CenterManager'), ('CenterBusinessManager', 'CenterBusinessManager'), ('MarketingHead', 'MarketingHead'), ('Registrar', 'Registrar'), ('Budgetary', 'Budgetary'), ('ICL', 'ICL'), ('SHS', 'SHS'), ('IHE', 'IHE')], default='Budgetary', max_length=50),
        ),
    ]
