# Generated by Django 2.2.1 on 2019-08-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190823_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermarketingprofile',
            old_name='role',
            new_name='status',
        ),
    ]
