# Generated by Django 2.2.1 on 2019-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190909_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_budgetary',
            field=models.BooleanField(default=False, verbose_name='BUDGETARY'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_icl',
            field=models.BooleanField(default=False, verbose_name='ICL'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_ihe',
            field=models.BooleanField(default=False, verbose_name='IHE'),
        ),
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='is_shs',
            field=models.BooleanField(default=False, verbose_name='SHS'),
        ),
    ]
