# Generated by Django 2.2.1 on 2019-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190823_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketingprofile',
            name='status',
            field=models.CharField(choices=[('CenterManager', 'CenterManager'), ('CenterBusinessManager', 'CenterBusinessManager'), ('MarketingHead', 'MarketingHead'), ('Registrar', 'Registrar'), ('Budgetary', 'Budgetary'), ('ICL', 'ICL'), ('SHS', 'SHS'), ('IHE', 'IHE')], max_length=50, null=True),
        ),
    ]
