# Generated by Django 2.2.1 on 2019-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICL_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ICL Contact Category',
                'verbose_name_plural': 'ICL Contact Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IHE_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'IHE Contact Category',
                'verbose_name_plural': 'IHE Contact Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SHS_ContactCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SHS Contact Category',
                'verbose_name_plural': 'SHS Contact Categories',
                'ordering': ('name',),
            },
        ),
    ]
