# Generated by Django 2.2.1 on 2019-10-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCalendar',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('revised', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activity Request',
                'verbose_name_plural': 'Activity Requests',
            },
        ),
        migrations.CreateModel(
            name='ActivityCalendarTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.task',),
        ),
        migrations.CreateModel(
            name='ActivityCalendarProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activitycalendar.ActivityCalendar')),
            ],
            options={
                'verbose_name_plural': 'Activity Process List',
                'permissions': [('can_create_activity_request', 'Can create activity request')],
            },
            bases=('viewflow.process',),
        ),
    ]
