# Generated by Django 2.2.1 on 2019-09-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(null=True)),
                ('arrival', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255, null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Collateral',
            },
        ),
        migrations.CreateModel(
            name='AssignTerritory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_choices', models.CharField(choices=[('DISTRICT I', 'DISTRICT I'), ('DISTRICT II', 'DISTRICT II'), ('DISTRICT III', 'DISTRICT III'), ('DISTRICT IV', 'DISTRICT IV'), ('DISTRICT V', 'DISTRICT V'), ('DISTRICT VI', 'DISTRICT VI')], max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AssignQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', models.DateField(unique=True)),
                ('end_month', models.DateField(unique=True)),
                ('a_senior_high', models.BigIntegerField(null=True)),
                ('a_higher_education', models.BigIntegerField(null=True)),
                ('a_retail', models.BigIntegerField(null=True)),
                ('a_corporate', models.BigIntegerField(null=True)),
                ('a_owwa', models.BigIntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
