# Generated by Django 2.2.1 on 2019-09-26 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketinghead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignterritory',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='assignterritory',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assign_territory_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignterritory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='assignterritory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='collateral',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
    ]
