# Generated by Django 2.2.1 on 2019-09-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
