# Generated by Django 2.2.1 on 2019-09-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='quantity',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='unit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
