# Generated by Django 2.2.1 on 2019-09-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0002_auto_20190909_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='c_amount',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='c_name',
        ),
        migrations.AlterField(
            model_name='collateral',
            name='quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
