# Generated by Django 2.2.1 on 2019-09-09 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0003_auto_20190909_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='title',
        ),
    ]
