# Generated by Django 2.2.1 on 2019-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0004_remove_budget_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
