# Generated by Django 2.2.1 on 2019-09-09 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketinghead', '0005_budget_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='b_amount',
            new_name='amount',
        ),
    ]
