# Generated by Django 2.2.1 on 2019-11-02 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('activity_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'pending 1 '), (2, 'pending 2'), (3, 'pending 3'), (4, 'apppoved 1'), (5, 'apppoved 2'), (6, 'apppoved 3'), (7, 'revised 1'), (8, 'revised 2'), (9, 'revised 3'), (10, 'rejected'), (11, 'cancelled')], default=0, protected=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Request',
                'verbose_name_plural': 'Activity Requests',
            },
        ),
    ]
