# Generated by Django 2.2.1 on 2019-11-07 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='flyer_ihe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='flyer_nc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='flyer_shs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='standy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tarpaulin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'pending 1 '), (2, 'apppoved 1'), (3, 'revised 1'), (4, 'pending 2'), (5, 'apppoved 2'), (6, 'revised 2'), (7, 'pending 3'), (8, 'apppoved 3'), (9, 'revised 3'), (10, 'rejected'), (11, 'cancelled')], default=0, protected=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
