# Generated by Django 2.2.1 on 2019-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourseModel',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255, null=True)),
                ('course_subject', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Available Course',
            },
        ),
        migrations.CreateModel(
            name='RequirementsModel',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('corporate_req', models.CharField(max_length=255, null=True)),
                ('retail_req', models.CharField(max_length=255, null=True)),
                ('owwa_req', models.CharField(max_length=255, null=True)),
                ('senior_high_req', models.CharField(max_length=255, null=True)),
                ('higher_ed_req', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Requirements',
            },
        ),
    ]
