# Generated by Django 2.2.1 on 2019-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20190909_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablecoursemodel',
            name='course_subject',
        ),
        migrations.AddField(
            model_name='availablecoursemodel',
            name='course_unit',
            field=models.SmallIntegerField(null=True),
        ),
    ]
