# Generated by Django 2.2.1 on 2019-09-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20190909_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablecoursemodel',
            old_name='course_unit',
            new_name='number_unit',
        ),
    ]
