# Generated by Django 2.2.1 on 2019-09-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_auto_20190909_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Requirements Category',
                'verbose_name_plural': 'Requirements Categories',
                'ordering': ('name',),
            },
        ),
        migrations.RenameField(
            model_name='requirementsmodel',
            old_name='corporate_req',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='higher_ed_req',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='owwa_req',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='retail_req',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='senior_high_req',
        ),
        migrations.RemoveField(
            model_name='requirementsmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='requirementsmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.RequirementsCategory'),
        ),
    ]
